# Generated by Django 5.2.3 on 2025-07-01 09:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GooglePlayApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_name", models.CharField(max_length=500)),
                ("category", models.CharField(max_length=100)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("reviews_count", models.IntegerField(default=0)),
                ("size", models.CharField(max_length=50)),
                ("installs", models.CharField(max_length=50)),
                ("app_type", models.CharField(max_length=20)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("content_rating", models.CharField(max_length=50)),
                ("genres", models.CharField(max_length=200)),
                ("last_updated", models.CharField(max_length=50)),
                ("current_version", models.CharField(max_length=50)),
                ("android_version", models.CharField(max_length=50)),
            ],
            options={
                "ordering": ["-rating", "-reviews_count"],
            },
        ),
        migrations.CreateModel(
            name="ExistingReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_text", models.TextField()),
                ("sentiment", models.CharField(default="Neutral", max_length=20)),
                ("sentiment_polarity", models.FloatField(default=0.0)),
                ("sentiment_subjectivity", models.FloatField(default=0.0)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="existing_reviews",
                        to="apps.googleplayapp",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_text", models.TextField()),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("Positive", "Positive"),
                            ("Negative", "Negative"),
                            ("Neutral", "Neutral"),
                        ],
                        default="Neutral",
                        max_length=20,
                    ),
                ),
                ("sentiment_polarity", models.FloatField(default=0.0)),
                ("sentiment_subjectivity", models.FloatField(default=0.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_reviews",
                        to="apps.googleplayapp",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
