# Generated by Django 5.2.3 on 2025-07-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0002_userreview_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userreview",
            name="sentiment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Positive", "Positive"),
                    ("Negative", "Negative"),
                    ("Neutral", "Neutral"),
                ],
                default="Neutral",
                max_length=20,
                null=True,
            ),
        ),
    ]
